# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sth < Formula
  desc "Skills Transfer Hub CLI — install reusable AI skills, agents and commands."
  homepage "https://github.com/Skills-transfer-hub/sth-releases"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skills-transfer-hub/sth-releases/releases/download/v0.2.0/sth-darwin-amd64.tar.gz"
      sha256 "ba0ce2f7ac088400fbe92bfe985f72164388ab87353df4dd941f3de2edb5d534"

      define_method(:install) do
        bin.install "sth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skills-transfer-hub/sth-releases/releases/download/v0.2.0/sth-darwin-arm64.tar.gz"
      sha256 "7bc64b122bed7e1562ae0a02ed362908030bfd3b3703f11dd46a15c61d4293cb"

      define_method(:install) do
        bin.install "sth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skills-transfer-hub/sth-releases/releases/download/v0.2.0/sth-linux-amd64.tar.gz"
      sha256 "1248f25c1ba60ef3b7963ea54989dd4882d0010e30f3d2dc0ad2bfa876387793"
      define_method(:install) do
        bin.install "sth"
      end
    end
  end

  test do
    assert_match "STH", shell_output("#{bin}/sth version")
  end
end
