# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sth < Formula
  desc "Skills Transfer Hub (Alpha) — CLI to install AI skills from a hosted catalog."
  homepage "https://github.com/Skills-transfer-hub/sth-releases"
  version "0.2.42"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skills-transfer-hub/sth-releases/releases/download/v0.2.42/sth-darwin-amd64.tar.gz"
      sha256 "50d9cda01a20dede07356d9d64d85d137f5832caddf0cb2a6dc773e81b6b6d9b"

      define_method(:install) do
        bin.install "sth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skills-transfer-hub/sth-releases/releases/download/v0.2.42/sth-darwin-arm64.tar.gz"
      sha256 "ca34dc7c5b2114ade8a65de5bdb7596573b2ce6890cb8e9fa759460d0515f41e"

      define_method(:install) do
        bin.install "sth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skills-transfer-hub/sth-releases/releases/download/v0.2.42/sth-linux-amd64.tar.gz"
      sha256 "1f0f321acfd4f47a5d4869155703558e32c2cf41df3d9d54a30fedf0e3fabf80"
      define_method(:install) do
        bin.install "sth"
      end
    end
  end

  test do
    assert_match "STH", shell_output("#{bin}/sth version")
  end
end
