# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sth < Formula
  desc "Skills Transfer Hub — CLI to install AI skills from a hosted catalog."
  homepage "https://github.com/Grandpied33/sth-releases"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Grandpied33/sth-releases/releases/download/v0.2.2/sth-darwin-amd64.tar.gz"
      sha256 "40dfc859e306a7c33f13a4f7bc10865e8fe9ab549552cd3e0bab3f4432deade8"

      define_method(:install) do
        bin.install "sth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Grandpied33/sth-releases/releases/download/v0.2.2/sth-darwin-arm64.tar.gz"
      sha256 "ae781e55d499d514370190d06687373547380aa4a31b521e95a6b70b98b91e3a"

      define_method(:install) do
        bin.install "sth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Grandpied33/sth-releases/releases/download/v0.2.2/sth-linux-amd64.tar.gz"
      sha256 "c67f4a1510ffb425d11de11d86c645fff7c65377b865e551a27703df2cc0aff5"
      define_method(:install) do
        bin.install "sth"
      end
    end
  end

  test do
    assert_match "STH", shell_output("#{bin}/sth version")
  end
end
